<?php
return array (
  'wenp' => 
  array (
    'fieldid' => '113',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'wenp',
    'name' => '学历',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 'array (
  \'linkageid\' => \'3364\',
  \'showtype\' => \'0\',
  \'space\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '3364',
    'showtype' => '0',
    'space' => '',
  ),
  'zili' => 
  array (
    'fieldid' => '114',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'zili',
    'name' => '讲师资历',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'36\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '36',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'shengy' => 
  array (
    'fieldid' => '115',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'shengy',
    'name' => '音频介绍',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
  \'show_type\' => \'0\',
  \'upload_maxsize\' => \'5000\',
  \'upload_allowext\' => \'mp3|wav|wma\',
  \'isselectimage\' => \'0\',
  \'images_width\' => \'\',
  \'images_height\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
    'show_type' => '0',
    'upload_maxsize' => '5000',
    'upload_allowext' => 'mp3|wav|wma',
    'isselectimage' => '0',
    'images_width' => '',
    'images_height' => '',
  ),
  'sex' => 
  array (
    'fieldid' => '120',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'sex',
    'name' => '性别',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'男|男
女|女\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '男|男
女|女',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
  ),
  'shengri' => 
  array (
    'fieldid' => '121',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'shengri',
    'name' => '生日',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 'array (
  \'fieldtype\' => \'date\',
  \'format\' => \'Y-m-d Ah:i:s\',
  \'defaulttype\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'fieldtype' => 'date',
    'format' => 'Y-m-d Ah:i:s',
    'defaulttype' => '0',
  ),
  'xuexiao' => 
  array (
    'fieldid' => '122',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'xuexiao',
    'name' => '学校',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'30\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '30',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'aihao' => 
  array (
    'fieldid' => '123',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'aihao',
    'name' => '爱好',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'看书|看书
跑步|跑步
打球|打球
上网|上网
旅游|旅游\',
  \'boxtype\' => \'checkbox\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'width\' => \'100\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
  \'outputtype\' => \'1\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '看书|看书
跑步|跑步
打球|打球
上网|上网
旅游|旅游',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '',
    'outputtype' => '1',
  ),
  'skype' => 
  array (
    'fieldid' => '111',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'skype',
    'name' => 'skype账号',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'36\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '1',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '36',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'jianjie' => 
  array (
    'fieldid' => '112',
    'modelid' => '12',
    'siteid' => '0',
    'field' => 'jianjie',
    'name' => '简介',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 'array (
  \'toolbar\' => \'basic\',
  \'defaultvalue\' => \'\',
  \'allowupload\' => \'0\',
  \'enablesaveimage\' => \'0\',
  \'height\' => \'200\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '1',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '2',
    'disabled' => '0',
    'isomnipotent' => '0',
    'toolbar' => 'basic',
    'defaultvalue' => '',
    'allowupload' => '0',
    'enablesaveimage' => '0',
    'height' => '200',
  ),
);
?>