<?php
return array (
  'title' => '预约时间段',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '07:00',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3361',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '07:30',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3362',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '08:00',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3363',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '08:30',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3369',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '09:00',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '09:30',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '10:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '10:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '11:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '11:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '12:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '12:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '13:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '13:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '14:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '14:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '15:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '15:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '16:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '16:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '17:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '17:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '18:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '18:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '19:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '19:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '20:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '20:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '21:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '21:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '22:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '22:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '23:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '23:30',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '24:00',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>